project_id = "nxrfefajarnzctdjbbrb"

[functions.lookup-representative]
verify_jwt = false

[functions.summarize-bill]
verify_jwt = false

[functions.generate-arguments]
verify_jwt = false

[functions.sync-congress-bills]
verify_jwt = false

[functions.sync-govtrack-bills]
verify_jwt = false

[functions.sync-openstates-bills]
verify_jwt = false

[functions.sync-legislative-data]
verify_jwt = false

[functions.generate-bill-stages]
verify_jwt = false

[functions.analyze-bill-impact]
verify_jwt = false

[functions.bill-buddy-chat]
verify_jwt = false
